baseURL = "https://alphaimpresiones.pages.dev/"
googleAnalytics = ""
theme = "hyde"
publishDir = "public"
languageCode = 'es'
title = 'Alpha Impresiones'

[taxonomies]
categoria = "categorias"


[params]
description = "Portfolio Impresiones 3D"
logo = "/imagen/logo/logo.png"
gif = "/imagen/logo/3d.webp"
shops = "/imagen/logo/mercado-shops.png"
oferta = "/imagen/logo/ofertas.png"
propaganda = "/imagen/propaganda.png"
propagandaMovil = "/imagen/propaganda-movil.png"
adsense_id = "ca-pub-1467437251743895"

[[params.categorias]]
  titulo = "Souveniers"
  slug = "souveniers"

[[params.categorias]]
  titulo = "Ofertas"
  slug = "ofertas"

[[params.categorias]]
  titulo = "Jugueteria"
  slug = "jugueteria"

[[params.categorias]]
  titulo = "Games"
  slug = "games"

[[params.categorias]]
  titulo = "Kids"
  slug = "kids"



[menu]

[[menu.main]]
  identifier = "contacto"
  name = "Contacto"
  title = "Contacto"
  url = "/contacto/"
  weight = 0

  [[menu.main]]
  identifier = "politica-de-privacidad"
  name = "Politica de Privacidad"
  title = "Politica de Privacidad"
  url = "/politica-de-privacidad/"
  weight = 9

[[menu.main]]
  parent = "Modelos de Llaveros"
  identifier = "disney-moment"
  name = "Disney Moment"
  title = "Disney Moment"
  url = "/llaveros/disney/"
  weight = 1

[[menu.main]]
  parent = "Modelos de Llaveros"
  identifier = "flork"
  name = "FLORK"
  title = "FLORK"
  url = "/llaveros/flork/"
  weight = 2

[[menu.main]]
  parent = "Modelos de Llaveros"
  identifier = "mario"
  name = "Mario World"
  title = "Mario World"
  url = "/llaveros/mario"
  weight = 3

[[menu.main]]
  parent = "Modelos de Llaveros"
  identifier = "mickey"
  name = "Mickey"
  title = "Mickey"
  url = "/llaveros/mickey"
  weight = 4

[[menu.main]]
  parent = "Modelos de Llaveros"
  identifier = "minecraft"
  name = "Minecraft"
  title = "Minecraft"
  url = "/llaveros/minecraft"
  weight = 5

[[menu.main]]
  parent = "Modelos de Llaveros"
  identifier = "minions"
  name = "Minions"
  title = "Minions"
  url = "/llaveros/minion"
  weight = 6

[[menu.main]]
  parent = "Clubes Futbol"
  identifier = "clubes"
  name = "Clubes "
  title = "Clubes"
  url = "/llaveros/clubes"
  weight = 7

[[menu.main]]
  identifier = "fotos"
  name = "PEDIDOS de Clientes"
  title = "fotos"
  url = "/fotos"
  weight = 8

